<?php
/**
 * Created by PhpStorm.
 * User: CETCA
 * Date: 2018/10/10
 * Time: 下午2:35
 */
namespace app\api\controller\v1;

use app\api\controller\Api;
use app\api\controller\Jwt;
use think\Config;
use think\Request;
use think\Session;

class Demo extends Api {

    public function _initialize()
    {
        if (in_array(Request::instance()->action(),['encode','decode'])){
            $this->apiAuth=false;
        }
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function encode(){
        $token=Jwt::encode(['user_id'=>1,'age'=>2,'time'=>time(),'session_exp'=>Config::get('expare')],Config::get('jwt_key'));
        Session::set('jwt:'.$token,$token);
        return $token;
    }

    public function decode(){
        $token=Request::instance()->header('token');
        $playload=Jwt::decode($token,Config::get('jwt_key'));

        var_dump($playload);
    }
}